# -*- coding: utf-8 -*-
"""TestRequest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScOz4ASlynincnpbJdNrFji81Bfs1Amk

## Test request
"""

import requests
import numpy as np
import json

url = "http://127.0.0.1:5000/predict"
sample_image = np.random.rand(28, 28).tolist()

data = json.dumps({"image": sample_image})
response = requests.post(url, data=data, headers={"Content-Type": "application/json"})

print(response.json())
